name: CD Mirroring

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  code_checker:
    name: Checking the code
    if: ${{ !startsWith(github.repositoryUrl, 'git://github.com/EpitechPromo2027') }}
    uses: ./.github/workflows/code_checker.yml

  repository_mirroring:
    name: Cloning the repository to Epitech
    runs-on: ubuntu-latest

    needs: [ code_checker ]
    if: needs.code_checker.result == 'success'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Repository mirroring
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ secrets.REPO_URL_PROD }}
        ssh_private_key:
          ${{ secrets.MIRROR_KEY }}
